window.coupleConfig = {
  password: "071222",
  names: {
    left: "小朱",
    right: "婧婧大王",
    display: "小朱 & 婧婧大王",
  },
  startedAt: "2025-09-12T00:00:00+08:00",
  hero: {
    eyebrow: "SINCE 2025.09.12",
    title: "我们已经在一起",
    note: "从 2025 年 9 月 12 日开始，普通的日子也被认真收藏。",
  },
  letter: {
    title: "把喜欢放进日历",
    body:
      "愿每一次靠近、每一次拥抱、每一个被记住的小日子，都在这里慢慢发光。",
  },
  calendar: {
    years: [2026, 2027],
    initialYear: 2026,
    title: "我们的纪念日历",
    subtitle: "生日、相爱日、整百天和官方节假日，都会被认真圈起来。",
    pendingNoticeByYear: {
      2027: "2027 年节日日期已标出，官方放假调休待发布。",
    },
    featured: [
      { label: "相爱日", month: 9, day: 12, tone: "mint", kind: "private" },
    ],
    festivalsByYear: {
      2026: [
        { label: "元旦", month: 1, day: 1, tone: "gold", kind: "festival" },
        { label: "除夕", month: 2, day: 16, tone: "rose", kind: "festival" },
        { label: "春节", month: 2, day: 17, tone: "rose", kind: "festival" },
        { label: "清明节", month: 4, day: 5, tone: "mint", kind: "festival" },
        { label: "劳动节", month: 5, day: 1, tone: "pink", kind: "festival" },
        { label: "端午节", month: 6, day: 19, tone: "blue", kind: "festival" },
        { label: "中秋节", month: 9, day: 25, tone: "gold", kind: "festival" },
        { label: "国庆节", month: 10, day: 1, tone: "rose", kind: "festival" },
      ],
      2027: [
        { label: "元旦", month: 1, day: 1, tone: "gold", kind: "festival" },
        { label: "除夕", month: 2, day: 5, tone: "rose", kind: "festival" },
        { label: "春节", month: 2, day: 6, tone: "rose", kind: "festival" },
        { label: "清明节", month: 4, day: 5, tone: "mint", kind: "festival" },
        { label: "劳动节", month: 5, day: 1, tone: "pink", kind: "festival" },
        { label: "端午节", month: 6, day: 9, tone: "blue", kind: "festival" },
        { label: "中秋节", month: 9, day: 15, tone: "gold", kind: "festival" },
        { label: "国庆节", month: 10, day: 1, tone: "rose", kind: "festival" },
      ],
    },
    officialHolidayArrangementsByYear: {
      2026: [
        { label: "元旦休假", month: 1, day: 1, dayText: "01-03", tone: "holiday", kind: "holiday" },
        { label: "调休上班", month: 1, day: 4, tone: "work", kind: "workday" },
        { label: "春节休假", month: 2, day: 15, dayText: "15-23", tone: "holiday", kind: "holiday" },
        { label: "调休上班", month: 2, day: 14, tone: "work", kind: "workday" },
        { label: "调休上班", month: 2, day: 28, tone: "work", kind: "workday" },
        { label: "清明休假", month: 4, day: 4, dayText: "04-06", tone: "holiday", kind: "holiday" },
        { label: "劳动节休假", month: 5, day: 1, dayText: "01-05", tone: "holiday", kind: "holiday" },
        { label: "调休上班", month: 5, day: 9, tone: "work", kind: "workday" },
        { label: "端午休假", month: 6, day: 19, dayText: "19-21", tone: "holiday", kind: "holiday" },
        { label: "中秋休假", month: 9, day: 25, dayText: "25-27", tone: "holiday", kind: "holiday" },
        { label: "国庆休假", month: 10, day: 1, dayText: "01-07", tone: "holiday", kind: "holiday" },
        { label: "调休上班", month: 9, day: 20, tone: "work", kind: "workday" },
        { label: "调休上班", month: 10, day: 10, tone: "work", kind: "workday" },
      ],
      2027: [],
    },
  },
  anniversaries: [
    {
      title: "第一次牵手已经",
      date: "2025-09-12",
      type: "elapsed",
      icon: "paw",
      tone: "peach",
      note: "那一天开始，掌心也有了方向。",
    },
    {
      title: "第一次拥抱已经",
      date: "2025-09-12",
      type: "elapsed",
      icon: "hug",
      tone: "blue",
      note: "抱住的时候，世界安静了一点。",
    },
    {
      title: "520 还剩",
      date: "2026-05-20",
      type: "countdown",
      icon: "heart",
      tone: "rose",
      note: "把喜欢说得更认真一点。",
    },
    {
      title: "一周年纪念日还剩",
      date: "2026-09-12",
      type: "countdown",
      icon: "spark",
      tone: "gold",
      note: "从第一天走到第一年。",
    },
    {
      title: "情人节还剩",
      month: 2,
      day: 14,
      type: "yearly",
      icon: "rose",
      tone: "pink",
      note: "玫瑰、拥抱和一句我爱你。",
    },
    {
      title: "小朱的生日还剩",
      month: 8,
      day: 24,
      type: "yearly",
      icon: "cake",
      tone: "peach",
      note: "今天要被偏爱得更明显。",
    },
    {
      title: "婧婧大王的生日还剩",
      month: 2,
      day: 2,
      type: "yearly",
      icon: "cake",
      tone: "blue",
      note: "把祝福藏进每一盏灯里。",
    },
    {
      title: "300 天纪念日还剩",
      date: "2026-07-09",
      type: "countdown",
      icon: "spark",
      tone: "mint",
      note: "把第三个一百天认真圈起来。",
    },
    {
      title: "400 天纪念日还剩",
      date: "2026-10-17",
      type: "countdown",
      icon: "heart",
      tone: "rose",
      note: "又多攒了一百天的喜欢。",
    },
    {
      title: "500 天纪念日还剩",
      date: "2027-01-25",
      type: "countdown",
      icon: "spark",
      tone: "gold",
      note: "五百天，也要亮晶晶地庆祝。",
    },
    {
      title: "600 天纪念日还剩",
      date: "2027-05-05",
      type: "countdown",
      icon: "heart",
      tone: "pink",
      note: "继续把普通日子过成纪念。",
    },
    {
      title: "700 天纪念日还剩",
      date: "2027-08-13",
      type: "countdown",
      icon: "spark",
      tone: "blue",
      note: "第七个一百天，也想和你一起数。",
    },
    {
      title: "800 天纪念日还剩",
      date: "2027-11-21",
      type: "countdown",
      icon: "heart",
      tone: "peach",
      note: "把八百天写进温柔的日历。",
    },
    {
      title: "900 天纪念日还剩",
      date: "2028-02-29",
      type: "countdown",
      icon: "spark",
      tone: "mint",
      note: "很特别的一天，刚好也很值得记住。",
    },
    {
      title: "1000 天纪念日还剩",
      date: "2028-06-08",
      type: "countdown",
      icon: "heart",
      tone: "gold",
      note: "一千天，要认真说一声辛苦也幸福。",
    },
  ],
  timeline: [
    {
      date: "2025-09-12",
      title: "相爱的第一天",
      text: "后来再回头看，这一天像把一个小小的铃铛挂在了生活上。",
    },
    {
      date: "2025-09-12",
      title: "第一次牵手",
      text: "手心贴近的时候，未来突然变得很具体。",
    },
    {
      date: "2025-09-12",
      title: "第一次拥抱",
      text: "有些安心不用说出口，抱一下就全懂了。",
    },
    {
      date: "每一个普通日子",
      title: "继续一起",
      text: "把小事过成纪念，把今天也认真收藏。",
    },
  ],
  defaultWishes: [
    {
      id: "sunset",
      text: "想一起看很多很多次日落。",
    },
    {
      id: "year-by-year",
      text: "愿我们每一年都比去年更懂彼此。",
    },
    {
      id: "ordinary-days",
      text: "把普通日子也过得亮晶晶。",
    },
    {
      id: "good-night",
      text: "每天都认真说晚安。",
    },
  ],
  footer: "For 小朱 & 婧婧大王, since 2025.09.12.",
};
